site_name: ESG Sustainability Assistant
site_url: https://esg-sustainability-assistant.github.io

theme:
    name: material
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: black
          accent: teal
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - scheme: slate
          primary: black
          accent: teal
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
