FROM python:3.13-slim-trixie

COPY --from=ghcr.io/astral-sh/uv:0.8.15 /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock /app/

RUN pip install pydantic requests streamlit

COPY ./src/streamlit_app.py ./src/models/ /app/src/

EXPOSE 8501

CMD ["streamlit", "run", "src/streamlit_app.py"]
