FROM python:3.13-slim-trixie

COPY --from=ghcr.io/astral-sh/uv:0.8.15 /uv /uvx /bin/

RUN uv tool install crewai

RUN apt-get update && \
    apt-get install -y gcc g++ clang-17 build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /esg-sustainability-crew

COPY . /esg-sustainability-crew/

RUN uv run crewai install

CMD ["uv", "run", "uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "80"]